# Generated by Django 3.1.7 on 2021-02-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=64, verbose_name='Firma')),
                ('firma_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('firma_created_at', models.DateTimeField(auto_now_add=True)),
                ('firma_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_name', models.CharField(max_length=64, verbose_name='Name')),
                ('kunde_lager', models.CharField(max_length=64, verbose_name='Lager')),
                ('kunde_created_at', models.DateTimeField(auto_now_add=True)),
                ('kunde_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Firmenzugehörigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stammdaten.firma', verbose_name='Firma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
        ),
    ]
