# Generated by Django 3.1.7 on 2021-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=64, verbose_name='Firma')),
                ('firma_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('firma_created_at', models.DateTimeField(auto_now_add=True)),
                ('firma_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_name', models.CharField(max_length=64, verbose_name='Name')),
                ('kunde_lager', models.CharField(max_length=64, verbose_name='Lager')),
                ('kunde_created_at', models.DateTimeField(auto_now_add=True)),
                ('kunde_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
    ]
