# Generated by Django 3.1.7 on 2021-02-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grund_name', models.CharField(max_length=64, verbose_name='Name')),
                ('grund_created_at', models.DateTimeField(auto_now_add=True)),
                ('grund_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grund',
                'verbose_name_plural': 'Gründe',
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie_name', models.CharField(max_length=64, verbose_name='Name')),
                ('kategorie_created_at', models.DateTimeField(auto_now_add=True)),
                ('kategorie_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
    ]
