# Generated by Django 3.1.7 on 2021-02-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stammdaten', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grund_name', models.CharField(max_length=64, verbose_name='Grund')),
                ('grund_created_at', models.DateTimeField(auto_now_add=True)),
                ('grund_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grund',
                'verbose_name_plural': 'Gründe',
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie_name', models.CharField(max_length=64, verbose_name='Kategorie')),
                ('kategorie_created_at', models.DateTimeField(auto_now_add=True)),
                ('kategorie_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Reklamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reklamation_datum', models.DateTimeField(verbose_name='Datum')),
                ('reklamation_produkt', models.CharField(max_length=64, verbose_name='Produkt')),
                ('reklamation_menge', models.PositiveSmallIntegerField(verbose_name='Menge')),
                ('reklamation_bemerkung', models.CharField(max_length=200, verbose_name='Bemerkung')),
                ('reklamation_maßnahmen', models.CharField(max_length=200, verbose_name='Maßnahmen')),
                ('reklamation_vertriebsmaßnahme', models.CharField(max_length=200, verbose_name='Vertriebsmaßnahme')),
                ('reklamation_lieferschein', models.CharField(max_length=64, verbose_name='Lieferschein')),
                ('reklamation_lieferant', models.CharField(max_length=64, verbose_name='Lieferant')),
                ('reklamation_created_at', models.DateTimeField(auto_now_add=True)),
                ('reklamation_updated_at', models.DateTimeField(auto_now=True)),
                ('reklamation_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stammdaten.firma', verbose_name='Firma')),
                ('reklamation_grund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reklamation.grund', verbose_name='Grund')),
                ('reklamation_kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reklamation.kategorie', verbose_name='Kategorie')),
                ('reklamation_lager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stammdaten.kunde', verbose_name='Lager')),
                ('reklamation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Reklamation',
                'verbose_name_plural': 'Reklamationen',
            },
        ),
    ]
