# Generated by Django 3.1.7 on 2021-02-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0002_grund_kategorie'),
        ('reklamation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklamation',
            name='reklamation_Grund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stammdaten.grund', verbose_name='Grund'),
        ),
        migrations.AddField(
            model_name='reklamation',
            name='reklamation_Kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stammdaten.kategorie', verbose_name='Kategorie'),
        ),
    ]
